name: AMAS2026
channels:
- conda-forge
dependencies:
- python=3.13
- numpy>=2.0
- matplotlib
- scipy
- pandas
- sympy
- iminuit
- notebook
- ipython
- ipywidgets
- beautifulsoup4
- seaborn
- xgboost
- scikit-learn
